# Bug in isAggregate column?

### As of 2026-03-03 the dehaviour describe bellow is not true anymore.

The value of `isAggregate` column is affected by the values of the partner2Code column (and probably other detail columns like Mode of Transport and CustomsCode).

If a dataset has details of partner2 then `isAggregate` is set at the level of specific partner2, and not when partner2Code = 0

For example China-Angola Imports 2017

In [25]:
import comtradetools as comtradetools

comtradetools.setup()
APIKEY = comtradetools.get_api_key()
comtradetools.init(APIKEY, force_init=False)

china_code = comtradetools.decode_country(24)
angola_code = comtradetools.decode_country(156)
china_code, angola_code

('Angola', 'China')

In [30]:
# pip install pandas requests

import json
import requests
import pandas as pd
from comtradetools import encode_country


pd.set_option('display.float_format', lambda x: '%.2f' % x)

china_code = encode_country('China')
angola_code = encode_country('Angola')
url_cn_angola_2017 = f"https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode={china_code}&period=2017&partnerCode={angola_code}&flowCode=M&customsCode=C00"
resp = requests.get(url_cn_angola_2017)
results = json.loads(resp.content)['data']
df_2017 = pd.DataFrame(results)
# df_2017.info()
df_2017[['refYear','cmdCode','partner2Code','isAggregate','primaryValue']].sort_values(by='cmdCode').head(20)

    refYear cmdCode  partner2Code  isAggregate   primaryValue
0      2017   TOTAL             0         True 20698709467.00
14     2017   TOTAL           764         True         856.00
13     2017   TOTAL           757         True        4765.00
12     2017   TOTAL           752         True         348.00
11     2017   TOTAL           702         True       39756.00
10     2017   TOTAL           458         True  1108444330.00
9      2017   TOTAL           410         True   102717790.00
15     2017   TOTAL           826         True         882.00
8      2017   TOTAL           392         True   152009806.00
6      2017   TOTAL           360         True    87082773.00
5      2017   TOTAL           344         True   293358324.00
4      2017   TOTAL           276         True        2530.00
3      2017   TOTAL           178         True    54140525.00
2      2017   TOTAL            36         True        1699.00
1      2017   TOTAL            24         True 18900898236.00
7      2017   TOTAL           380         True        5119.00
16     2017   TOTAL           842         True        1728.00

In [31]:
# show only rows where isAggregate is False
df_2017[df_2017['isAggregate'] == False][['refYear','cmdCode','partner2Code','isAggregate','primaryValue']].sort_values(by='cmdCode').head(10)

Empty DataFrame
Columns: [refYear, cmdCode, partner2Code, isAggregate, primaryValue]
Index: []

Groupping by code delivers the expected results

In [32]:
pd.options.display.float_format = '{:,.2f}'.format
df_2017['cmdCodeAG2'] = df_2017.cmdCode.str[0:2]
df_2017[df_2017['isAggregate'] == False].groupby(['refYear','cmdCodeAG2']).agg({'primaryValue':'sum'}).reset_index().sort_values(by=['refYear','cmdCodeAG2'])

Empty DataFrame
Columns: [refYear, cmdCodeAG2, primaryValue]
Index: []

If the dataset has no breakdown if the partner2Code then the isAggregate value is set for lines with partner2Code = 0

In [33]:

url_cn_angola_2018 = 'https://comtradeapi.un.org/public/v1/preview//C/A/HS?reporterCode=156&period=2018&partnerCode=24&flowCode=M&customsCode=C00'
resp = requests.get(url_cn_angola_2018)
results = json.loads(resp.content)['data']
df_2018 = pd.DataFrame(results)
df_2018[['cmdCode','partner2Code','partner2Desc','isAggregate','primaryValue']].sort_values(by='cmdCode').head(20)

  cmdCode  partner2Code partner2Desc  isAggregate      primaryValue
0   TOTAL             0         None         True 25,826,510,355.00

In [34]:
pd.options.display.float_format = '{:,.2f}'.format
df_2018['cmdCodeAG2'] = df_2018.cmdCode.str[0:2]
df_2018[df_2018['isAggregate'] == False].groupby(['refYear','cmdCodeAG2']).agg({'primaryValue':'sum'}).reset_index().sort_values(by=['refYear','cmdCodeAG2'])

Empty DataFrame
Columns: [refYear, cmdCodeAG2, primaryValue]
Index: []

Resposta da Comtrade:

“This is not an issue with the data.
 
Some datasets have breakdown of 2ndPartner and some others do not, this will cause that flag to change depending on the original data received. For example:
 
https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=156&period=2017&partnerCode=24&flowCode=M&customsCode=C00&cmdCode=010612

https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=156&period=2019&partnerCode=24&flowCode=M&customsCode=C00&cmdCode=010612”
 
Best Regards
Comtrade Team

Nota: Os exemplos não especificam partnerCode2=0

In [35]:

# pip install pandas requests
import time
import json
import requests
import pandas as pd


pd.set_option('display.float_format', lambda x: '%.2f' % x)

url_cn_angola_2017 = 'https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=156&period=2017&partnerCode=24&flowCode=M&customsCode=C00'
resp = requests.get(url_cn_angola_2017)
results = json.loads(resp.content)['data']
df_2017 = pd.DataFrame(results)
print("As of 2023-02-17, the isAggregate column is correct for 2017 and earlier data if partner2Code is not specified, but duplicate rows are returned")
print("Request url: ", url_cn_angola_2017)
print(df_2017[['cmdCode','partner2Code','isAggregate','primaryValue']].sort_values(by='cmdCode').head(120))
print()

time.sleep(5)

url_cn_angola_2018 = 'https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=156&period=2019&partnerCode=24&flowCode=M&customsCode=C00'
resp = requests.get(url_cn_angola_2018)
results = json.loads(resp.content)['data']
df_2018 = pd.DataFrame(results)
print("As of 2023-02-18, the isAggregate column is correct for 2018 and later data, and there are no duplicates because partner2 always zero")
print("Request url: ", url_cn_angola_2018)
print(df_2018[['cmdCode','partner2Code','isAggregate','primaryValue']].sort_values(by='cmdCode').head(50))

As of 2023-02-17, the isAggregate column is correct for 2017 and earlier data if partner2Code is not specified, but duplicate rows are returned
Request url:  https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=156&period=2017&partnerCode=24&flowCode=M&customsCode=C00
   cmdCode  partner2Code  isAggregate   primaryValue
0    TOTAL             0         True 20698709467.00
14   TOTAL           764         True         856.00
13   TOTAL           757         True        4765.00
12   TOTAL           752         True         348.00
11   TOTAL           702         True       39756.00
10   TOTAL           458         True  1108444330.00
9    TOTAL           410         True   102717790.00
15   TOTAL           826         True         882.00
8    TOTAL           392         True   152009806.00
6    TOTAL           360         True    87082773.00
5    TOTAL           344         True   293358324.00
4    TOTAL           276         True        2530.00
3    TOTAL           178         True    54140525.00
2    TOTAL            36         True        1699.00
1    TOTAL            24         True 18900898236.00
7    TOTAL           380         True        5119.00
16   TOTAL           842         True        1728.00

As of 2023-02-18, the isAggregate column is correct for 2018 and later data, and there are no duplicates because partner2 always zero
Request url:  https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=156&period=2019&partnerCode=24&flowCode=M&customsCode=C00
  cmdCode  partner2Code  isAggregate   primaryValue
0   TOTAL             0         True 23837402142.00

In [36]:
df_2017[df_2017.isAggregate == False][['cmdCode','partner2Code','isAggregate','primaryValue']].sort_values(by='cmdCode').head(50)

Empty DataFrame
Columns: [cmdCode, partner2Code, isAggregate, primaryValue]
Index: []